added joinus
NobleMathews/CollegeBugle pull request #8
Opened 2022-06-16 12:54 UTC by Ganesh-P03

2022-06-16 16:37 UTC, NobleMathews requested changes
Nice work! please fix the 2 issues I highlighted it should good to go then

2022-06-16 16:37 UTC, NobleMathews commented on src/pages/about.js
> +            <Button>join us</Button>
Change to "JOIN US !", also the font doesn't seem to fit the rest of the page i feel could you have a look at that ?

2022-06-16 16:37 UTC, NobleMathews commented on src/pages/about.js
> +  padding: var(--sizing-sm) var(--sizing-base);
You might have t to change the padding used, currently if the row is full there is not enough spacing (ref https://i.imgur.com/EtmmZTW.png)

2022-06-18 05:52 UTC, Ganesh-P03 commented on src/pages/about.js
> +            <Button>join us</Button>
changed the text and font family!

2022-06-18 05:52 UTC, Ganesh-P03 commented on src/pages/about.js
> +  padding: var(--sizing-sm) var(--sizing-base);
Adjusted it

2022-06-18 19:44 UTC, merged